packages:
  - packages/*

catalog:
  "@cloudflare/vite-plugin": ^1.15.3
  "@phosphor-icons/react": ^2.1.10
  "@react-router/dev": ^7.9.6
  "@tailwindcss/cli": ^4.1.17
  "@tailwindcss/vite": ^4.1.17
  "@types/node": ^22.10.2
  "@types/react": 19.2.4
  "@types/react-dom": 19.2.3
  "@vitest/browser": ^3.2.4
  "@vitest/ui": ^3.2.4
  chokidar: ^4.0.3
  clsx: ^2.1.1
  eslint: ^9.17.0
  eslint-plugin-jsx-a11y: ^6.10.2
  happy-dom: ^20.0.2
  isbot: ^5.1.31
  playwright: ^1.57.0
  react: ^18.0.0 || ^19.0.0
  react-dom: ^18.0.0 || ^19.0.0
  react-error-boundary: ^6.0.0
  react-router: ^7.9.6
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.17
  tsx: ^4.19.2
  typescript: ^5.9.2
  vite: ^7.1.7
  vite-plugin-dts: ^4.3.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  oxlint: 1.42.0
  oxlint-tsgolint: 0.11.3
  wrangler: ^4.59.1
